"""Add flagged_by_user and flag_reason to Check

Revision ID: 8a8bd465c000
Revises: d5950ffb56eb
Create Date: 2025-05-21 16:41:18.068225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8bd465c000'
down_revision = 'd5950ffb56eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged_by_user', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('flag_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check', schema=None) as batch_op:
        batch_op.drop_column('flag_reason')
        batch_op.drop_column('flagged_by_user')

    # ### end Alembic commands ###
